name: CI/CD Pipeline (Disabled)

on:
  # Temporarily disable all triggers
  workflow_dispatch:
    # Manual trigger only

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Workflow temporarily disabled"