name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install Dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          
      - name: Install sshpass
        run: sudo apt-get install sshpass -y
          
      - name: Deploy to VM
        if: github.ref == 'refs/heads/main'
        env:
          HUNGRIA_PASSWORD: ${{ secrets.HUNGRIA_PASSWORD }}
          VM_PASSWORD: ${{ secrets.VM_PASSWORD }}
        run: |
          # Create SSH script for VM connection
          echo '#!/bin/bash
          sshpass -p "$1" ssh -p 4422 -o StrictHostKeyChecking=no sciledger@10.7.40.192 "
            cd /var/www/sciledger &&
            git pull origin main &&
            npm ci &&
            npm run build &&
            pm2 restart sciledger || pm2 start npm --name sciledger -- start
          "' > deploy_vm.sh
          
          # Make script executable
          chmod +x deploy_vm.sh
          
          # Connect to Hungria and execute VM deployment
          sshpass -p "$HUNGRIA_PASSWORD" ssh -p 4422 -o StrictHostKeyChecking=no leonardocabral@177.20.147.141 "
            $(cat deploy_vm.sh)" "$VM_PASSWORD"